name: Rust CI

on:
  push:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test code
        uses: actions/checkout@v5
        uses: dtolnay/rust-toolchain@stable
        run: cargo test --all --locked --verbose