name: Rust Test

on:
  push:
    branches:
      - '**'

jobs:
  test:
    name: Test code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test --all --locked