name: Create Dev Neuron
on:
    workflow_dispatch:
      inputs:
        deploy_message:
          description: 'Deployment message'
          required: false
          default: 'Manual deployment'
          type: string


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Publish canister artifacts and send upgrade proposals
    runs-on: ubuntu-latest
    permissions:
      packages: read
      contents: write

    steps:

      - name: Install quill from GitHub Releases
        run: |
          curl -LJO https://github.com/dfinity/quill/releases/download/v0.4.2/quill-linux-x86_64-musl
          mv quill-linux-x86_64-musl quill
          chmod +x quill
      - name: Stake Neuron
        run: |
          touch actions_identity.pem
          echo "${{ secrets.ESTATE_DAO_SNS_PROPOSAL_SUBMISSION_IDENTITY_PRIVATE_KEY }}" > actions_identity.pem
          # Create a new neuron with 1 ICP stake
          ./quill --pem-file actions_identity.pem neuron-stake \
            --amount 500 \
            --name "estate_N" > stake_request.json
          
          # Send the stake request
          ./quill send stake_request.json --yes  | tee stake_response.log
          
          # Wait for confirmation
          sleep 10
