name: Manage neuron
on:
    workflow_dispatch:
      inputs:
        deploy_message:
          description: 'Deployment message'
          required: false
          default: 'Manual deployment'
          type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Manage neuron
    runs-on: ubuntu-latest
    permissions:
      packages: read
      contents: write
    
    env:
      NEURON_ID: 8f9a87010a8d578a40be66eb7101aa4fd2d945fd44ff070c71771e53be2ff2ac
      DISSOLVE_DELAY_SECONDS: 16502400 # 191 days of dissolve delay
    
    steps:

      - name: Checkout repo and submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive
    
      # - name: Rust Setup
      #   uses: dtolnay/rust-toolchain@master
      #   with:
      #     toolchain: "nightly-2024-09-23"
      #     targets: "x86_64-unknown-linux-musl"
      #     components: ""
    
      # - uses: cargo-bins/cargo-binstall@main
      # - name: idl2json setup
      #   run: cargo binstall idl2json_cli --no-confirm

      - name: Install quill from GitHub Releases
        run: |
          curl -LJO https://github.com/dfinity/quill/releases/download/v0.4.2/quill-linux-x86_64-musl
          mv quill-linux-x86_64-musl quill
          chmod +x quill

      # - name: Stake Neuron
      #   run: |
      #     touch actions_identity.pem
      #     echo "${{ secrets.ESTATE_DAO_SNS_PROPOSAL_SUBMISSION_IDENTITY_PRIVATE_KEY }}" > actions_identity.pem
      #     ./quill --pem-file actions_identity.pem sns stake-neuron \
      #       --amount 500 --memo 69420 --canister-ids-file ./sns_canister_ids.json | tee stake_request.json
          
      #     # Send the stake request
      #     ./quill send stake_request.json --yes  | tee stake_response.log
          
      #     # Wait for confirmation
      #     sleep 10

      # - name: Extract NeuronID
      #   run: |
      #     awk '/^\( *$/ { inside_block=1 } inside_block { print }' stake_response.log  > output.txt
      #     NEURON_ID=$(cat output.txt | idl2json --bytes-as hex | jq -r '.command[0].ClaimOrRefresh.refreshed_neuron_id[0].id')
      #     echo "NEURON_ID=$NEURON_ID" >> $GITHUB_ENV
      #     echo "$NEURON_ID"
      
      - name: Add dissolve delay + other params
        run: | 
          touch actions_identity.pem
          echo "${{ secrets.ESTATE_DAO_SNS_PROPOSAL_SUBMISSION_IDENTITY_PRIVATE_KEY }}" > actions_identity.pem
      
          ./quill --pem-file actions_identity.pem  sns configure-dissolve-delay ${{env.NEURON_ID}} --additional-dissolve-delay-seconds ${{env.DISSOLVE_DELAY_SECONDS}} | tee manage_neuron.json

          sleep 10
